services:
  api:
    build: ../HarukabeServer
    env_file: ./env_file.env
    ports:
      - '8000:8000'
    volumes: 
      - '../HarukabeServer:/usr/src/app'
    tty: true
    stdin_open: true
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    # db作成後にコンテナ作成
    depends_on: 
      - db

  db:
    image: postgres:13
    env_file: ./env_file.env
    ports:
      - '5432:5432'
    volumes:
      - './db/:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: root

  client:
    build: ../HarukabeClient
    env_file: ./env_file.env
    ports:
      - '3000:3000'
    volumes:
      - '../HarukabeClient:/usr/src/app/'
        # - /usr/src/app/node_modules
    stdin_open: true
    tty: true
    # command: npm run dev

  nginx:
    image: nginx:latest
    env_file: ./env_file.env
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - client
